import localFont from "next/font/local";
import "./globals.css";
import "../main.css"
import Navbar from "./component/Navbar";
import Destination from "./component/Destination";
import Journey from "./component/Journey";
import Swim from "./component/Swim";
import Discover from "./component/Discover";
import Forms from "./component/Forms";
import Client from "./component/Client";
import Footer from "./component/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Forms/>
        <Destination/>
        <Journey/>
        <Swim/>
        <Discover/>
        <Client/>
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
